### ISSUE TITLE
Big list of workshops

### ISSUE THREAD

**Issue by clemsos** [leClub/leClub.github.io#3]
@MAKIO135 We need a big list of all possible workshops, so we can start selling them !

**Comment by MAKIO135** [comment]
Intro à Processing
Processing for Graphic Designers
Processing Advanced ( 3d, libs )
Processing Masterclass (dataviz, arduino + p5, p5.js, ... )
Intro à Arduino
Arduino Sensorshield
Intro à D3js
Datavisualisation with D3js
Intro à NodeJS
Realtime webapps with socket.io  ou MeteorJS
Web Tangible
Getting started with Raspberry Pi
Intro Python
Intro Grasshopper (avec Sam Javelle)
Grasshopper Advanced ( Gh + Processing / Gh +Arduino )
Le 14 févr. 2016 07:28, "Clément Renaud" notifications@github.com a
écrit :

**Comment by MAKIO135** [comment]
Dont les workshops déjà réalisés pour lesquels je peux faire un petit
article:
- Les ateliers P5Lyon
- Initiation Processing pour le Mirage Festival en 2014
- ProcessingJS pour les journées du code créatif à Nantes en 2014
- Arduino + Sensorshield lors de Processing Paris 2015
- Processing for Graphic Designers à Bellecour Arts Appliqués en Janvier
  2016

**Comment by clemsos** [comment]
Cool ! Voilà le système pour lister les workshops avec les posts _workshops ( c62e54d )

**Comment by MAKIO135** [comment]
include #22
