### ISSUE TITLE
Description du Workshop web tangible

### ISSUE THREAD

**Issue by clemsos** [leClub/leClub.github.io#8]
IL nousn le faut

**Comment by clemsos** [comment]
https://github.com/leClub/leClub.github.io/blob/master/_workshops/web-tangible.md

**Comment by MAKIO135** [comment]
Infos données au mirage:

 Web Tangible ( JS + Particle.io )

DESCRIPTIF :
Durant cette formation, vous apprendrez à créer et développer des expériences interactives mêlant web et réel. La première partie du workshop sera dédiée à l'initiation au pilotage d'un micro-contrôleur Particle Photon afin de récupérer les données de capteurs physiques, mais aussi afin d'agir sur des actionneurs (lumières, moteurs, ...). La seconde partie sera consacrée au web et la communication avec le micro-contrôleur. Enfin, la dernière partie de la formation sera réservée pour discuter de vos projets, et des solutions pratiques à mettre en place.

OBJECTIFS :
Découvrir l'utilisation d'un micro contrôleur Particle Photon.
S'initier à la programmation de capteurs et d'actionneurs.
Développer des procédés de communication entre le tangible et une interface numérique.
Créer des expériences interactives mêlant web et réel.

PUBLIC :
La formation est destinée à des designers interactifs, développeurs web, bidouilleurs numériques souhaitant prolonger des expériences web à l'espace physique, ou inversement, jouer avec des interactions physiques afin de manipuler un espace web.

PRE-REQUIS :
Aucune connaissance en micro contrôleur nécessaire.
Des bases en développement web (HTML/CSS).
Des notions en programmation Javascript.
Les stagiaires sont invités à venir munis de leur ordinateur personnel.
